export const STATUS_OK = 200;

export const START_LOADING = "START_LOADING";
export const STOP_LOADING = "STOP_LOADING";

export const DASHBOARD_STATISTICS = "DASHBOARD_STATISTICS";

export const LOGIN = "LOGIN";
export const FETCH_ROOM = "FETCH_ROOM";
export const FETCH_ROOM_BY_STATUS = "FETCH_ROOM_BY_STATUS";
export const FETCH_ROOM_BY_NAME = "FETCH_ROOM_BY_NAME";
export const SAVE_ROOM = "SAVE_ROOM";
export const DESECUPY_ROOM = "DESECUPY_ROOM";

export const FETCH_RESERVATIONS = "FETCH_RESERVATIONS";
export const FETCH_RESERVATIONS_BY_ROOM_NAME =
  "FETCH_RESERVATIONS_BY_ROOM_NAME";
export const SAVE_RESERVATION = "SAVE_RESERVATION";
export const CONFIRM_RESERVATION = "CONFIRM_RESERVATION";
export const CHECKOUT_RESERVATION = "CHECKOUT_RESERVATION";

export const FETCH_TENANT = "FETCH_TENANT";
export const UPDATE_REFRESH_TOKEN = "UPDATE_REFRESH_TOKEN";
