export const STATUS_OK = 200;

export const LOGIN = "LOGIN";
export const FETCH_ROOM = "FETCH_ROOM";
export const FETCH_ROOM_BY_STATUS = "FETCH_ROOM_BY_STATUS";
export const FETCH_ROOM_BY_NAME = "FETCH_ROOM_BY_NAME";
export const SAVE_ROOM = "SAVE_ROOM";
export const DESECUPY_ROOM = "DESECUPY_ROOM";

export const FETCH_RESERVATIONS = "FETCH_RESERVATIONS";
export const SAVE_RESERVATIONS = "SAVE_RESERVATIONS";
